name: medium_bloc_cache_project
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
